#servidor
server:
  host: localhost
  port: 8080
  tomcat:
    max-swallow-size: 800000000
    max-http-form-post-size: 80MB

aplicacao:
  versao: 1.6

#Spring
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        ddl-auto: none
    show-sql: false
    open-in-view: false
  datasource-auxtemp:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.0.70:49241;databaseName=Aux_Temp
    username: sistemas_ead
    password: sistemas_eadhmg258@
  datasource-lyceum:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.0.70:49241;databaseName=Lyceum
    username: sistemas_ead
    password: sistemas_eadhmg258@
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 100MB
      enabled: true

#LOGGING
logging:
  level:
    root: INFO
    com.sample.feign.demofeigncustomconfig: INFO
    br.edu.unicesumar: INFO
    org.springframework.web.client: INFO
    org.springframework.security.oauth2: INFO

quartz:
  job-store-type: memory
  properties:
    org:
      quartz:
        jobStore:
          isClustered: false
        threadPool:
          threadCount: 10

#autenticação OAuth2
security:
  oauth2:
    client:
      scope: password
      client-id: 607c6765-d6c9-4c20-a4ff-c373a3d50794
      client-secret: 5eabc608-8003-4105-8ed1-5cc45c7c5eb8

ws-config:
  urls:
    url-endpoint: http://webservicesh.unicesumar.edu.br/ead/soap/index.php?wsdl
    url-xsi: http://www.w3.org/2001/XMLSchema-instance
    url-xsd: http://www.w3.org/2001/XMLSchema
    url-soap-env: http://schemas.xmlsoap.org/soap/envelope/
  acesso:
    username: sydle.seed@unicesumar.edu.br
    password: cRA8edapRawu
