CREATE TABLE tb_cities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    state       VARCHAR(255)                            NOT NULL,
    country     VARCHAR(255)                            NOT NULL,
    date        VARCHAR(255)                            NOT NULL,
    temperature VARCHAR(255)                            NOT NULL,
    wind_speed  INTEGER                                 NOT NULL,
    dh_insert   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dh_update   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tb_cities PRIMARY KEY (id)
);