CREATE TABLE tb_cities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    state       VARCHAR(255)                            NOT NULL,
    country     VARCHAR(255)                            NOT NULL,
    date        DATE                                    NOT NULL,
    temp_min    double precision                        NOT NULL,
    temp_max    double precision                        NOT NULL,
    wind_speed  double precision                        NOT NULL,
    wind_deg    double precision                        NOT NULL,
    wind_gust   double precision                        NOT NULL
    CONSTRAINT pk_tb_cities PRIMARY KEY (id)
);